name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Test SSH echo
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: 22
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Connected to host: $HOSTNAME"
            echo "Running as user: $(whoami)"
