name: Deploy to EC2 Nginx Server

on:
  push:
    branches:
      - main  # Change to your deploy branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clean Nginx folder on server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          sudo rm -rf /usr/share/nginx/html/*
          sudo mkdir -p /usr/share/nginx/html
          sudo chown $USER:$USER /usr/share/nginx/html

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "."                      # or "build/" if you're deploying frontend assets
        target: "/usr/share/nginx/html"
        strip_components: 0
